export const classes = [
  {selector: 'Barbarian',
    val: 'Barbarian' },
  {selector: 'Bard',
    val: 'Bard' },
  {selector: 'Cleric',
    val: 'Cleric' },
  {selector: 'Druid',
    val: 'Druid' },
  {selector: 'Fighter',
    val: 'Fighter' },
  {selector: 'Monk',
    val: 'Monk' },
  {selector: 'Paladin',
    val: 'Paladin' },
  {selector: 'Ranger',
    val: 'Ranger' },
  {selector: 'Rogue',
    val: 'Rogue' },
  {selector: 'Sorcerer',
    val: 'Sorcerer' },
  {selector: 'Warlock',
    val: 'Warlock' },
  {selector: 'Wizard',
    val: 'Wizard' },
];
